/*
 * ------------------------------------------------------------------
 * This source code, its documentation and all appendant files
 * are protected by copyright law. All rights reserved.
 *
 * Copyright (C) 2012
 * Novartis Institutes for BioMedical Research
 *
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License, Version 3, as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 *  Additional permission under GNU GPL version 3 section 7:
 *
 *  KNIME interoperates with ECLIPSE solely via ECLIPSE's plug-in APIs.
 *  Hence, KNIME and ECLIPSE are both independent programs and are not
 *  derived from each other. Should, however, the interpretation of the
 *  GNU GPL Version 3 ("License") under any applicable laws result in
 *  KNIME and ECLIPSE being a combined program, KNIME GMBH herewith grants
 *  you the additional permission to use and propagate KNIME together with
 *  ECLIPSE with only the license terms in place for ECLIPSE applying to
 *  ECLIPSE and the GNU GPL Version 3 applying for KNIME, provided the
 *  license terms of ECLIPSE themselves allow for the respective use and
 *  propagation of ECLIPSE together with KNIME.
 *
 *  Additional permission relating to nodes for KNIME that extend the Node
 *  Extension (and in particular that are based on subclasses of NodeModel,
 *  NodeDialog, and NodeView) and that only interoperate with KNIME through
 *  standard APIs ("Nodes"):
 *  Nodes are deemed to be separate and independent programs and to not be
 *  covered works.  Notwithstanding anything to the contrary in the
 *  License, the License does not apply to Nodes, you are not required to
 *  license Nodes under the License, and you are granted a license to
 *  prepare and propagate Nodes, in each case even if such Nodes are
 *  propagated with or for interoperation with KNIME.  The owner of a Node
 *  may freely choose the license terms applicable to such Node, including
 *  when such Node is propagated with or for interoperation with KNIME.
 * ---------------------------------------------------------------------
 */
package org.rdkit.knime.nodes.interactivetable;

import org.knime.core.data.DataTableSpec;
import org.knime.core.node.BufferedDataTable;
import org.knime.core.node.ExecutionContext;
import org.knime.core.node.InvalidSettingsException;
import org.knime.core.node.NodeLogger;
import org.rdkit.knime.nodes.AbstractRDKitNodeModel;
import org.rdkit.knime.nodes.TableViewSupport;
import org.rdkit.knime.util.InputDataInfo;

/**
 * This class implements the node model of the RDKitInteractiveTable node
 * providing a view for data generated by RDKit nodes. It has the capability
 * to show additional header information like Smiles structures and
 * behaves for everything else like the normal interactive table from KNIME.
 * 
 * @author Manuel Schwarze 
 */
public class RDKitInteractiveTableNodeModel extends AbstractRDKitNodeModel implements TableViewSupport {

	//
	// Constants
	//
	
	/** The logger instance. */
	protected static final NodeLogger LOGGER = NodeLogger
			.getLogger(RDKitInteractiveTableNodeModel.class);
    
    //
    // Constructor
    //
    
    /**
     * Create new node model with one data in- and one out-port.
     */
    RDKitInteractiveTableNodeModel() {
        super(1, 1);
    }

    //
    // Public Methods
    //
    
    /**
     * This implementation just returns [ 0 ].
     * {@inheritDoc}
     * @return [ 0 ].
     */
    @Override
    public int[] getOutputTablesToConserve() {
    	return new int[] { 0 };
    }

    //
    // Protected Methods
    //
   
    /**
     * This implementation just returns the input table spec.
     * {@inheritDoc}
     */
    @Override
    protected DataTableSpec[] configure(final DataTableSpec[] inSpecs)
            throws InvalidSettingsException {
    	// Reset warnings and check RDKit library readiness
    	super.configure(inSpecs);
        return inSpecs;
    }

    /**
     * This implementation just returns null.
     * {@inheritDoc}
     */
	protected InputDataInfo[] createInputDataInfos(int inPort, DataTableSpec inSpec)
		throws InvalidSettingsException {    	
    	return null;
    }

    /**
     * This implementation just returns the input spec of the specified outport.
     * {@inheritDoc}
     */
	@Override
	protected DataTableSpec getOutputTableSpec(int outPort,
			DataTableSpec[] inSpecs) throws InvalidSettingsException {
		return inSpecs[outPort];
	}
    /**
     * This implementation just returns the input table(s).
     * {@inheritDoc}
     */
    @Override
    protected BufferedDataTable[] processing(BufferedDataTable[] inData,
    		InputDataInfo[][] arrInputDataInfo, ExecutionContext exec)
    		throws Exception {
    	return inData;
    }
}
